/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:b70c2f21-7303-431d-bec5-df5dd00a2ed1",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_ujG1RyLr3",
    "aws_user_pools_web_client_id": "isglekqvqr6iag2aoo14465iv",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "resumeparser5f75cf7a7224428eaf10580efc962b24c2109-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1",
    "aws_dynamodb_all_tables_region": "ap-south-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "ResumesTable-dev",
            "region": "ap-south-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://akn2wpwgqbbtxp435z4w73neoa.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5gn3bferbrczdc3eskteuwgru4"
};


export default awsmobile;
